apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./subscription.yaml
patchesJson6902:
  - target:
      group: operators.coreos.com
      version: v1alpha1
      kind: Subscription
      name: serverless-operator
      namespace: openshift-operators
    path: patch.yaml



